# Generated by Django 6.0.5 on 2026-06-02 10:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_alter_jobapplication_cv_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='jobadvert',
            name='application_fee',
        ),
        migrations.RemoveField(
            model_name='jobapplication',
            name='paid_amount',
        ),
        migrations.RemoveField(
            model_name='jobapplication',
            name='payment_status',
        ),
    ]
