# Generated by Django 6.0.5 on 2026-05-23 08:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='account',
            name='user_type',
            field=models.CharField(choices=[('EMPLOYER', 'Employer'), ('JOB_SEEKER', 'Job Seeker')], default='jobseeker', max_length=20),
        ),
    ]
